Repository advanced-security/codeql-queries, pull requests merged in 2022-07, with the labels that each got.

#40 Local Sources test cases and False Positives with `tempfile`
  .gitignore
  .vimignore
  python/github/LocalSources.qll
  tests/python-tests/libraries/localsources/LocalSourcesTest.expected
  tests/python-tests/libraries/localsources/app.py
Labels: python

#38 Add LocalSources Support for future Go Queries
  .codeqlmanifest.json
  .gitignore
  go/github/LocalSources.qll
  go/qlpack.yml
  tests/go-tests/qlpack.lock.yml
  tests/go-tests/qlpack.yml
Labels: go

#41 Update XXELocal source to SafeSaxSource
  java/CWE-611/XXELocal.ql
Labels: java

#42 Update unit testing Action steps
  .github/workflows/build.yml
  .github/workflows/update-submodules.yml
Labels: enhancement

#43 Update update-submodules.yml
  .github/workflows/update-submodules.yml
Labels: enhancement
